### ISSUE TITLE
Do the first release

### ISSUE THREAD

**Issue by madebr** [kulp/naive-tsearch#5]
I"d like to make a first release soon.
That way, I can create a package for naive-tsearch on [conan-center-index](https://github.com/conan-io/conan-center-index/) for a tagged version instead of a commit hash.

Things to do/consider before doing the tagging:
- [ ] Is version 0.1 ok?
- [ ] Is it ok to set the version only in CMakeLists.txt in the `project` call?
  We could eventually create a `VERSION` file that only contains the version.
- [ ] Modify the required boost version in the conanfile.py to use version ranges.

Are there other considerations?

**Comment by kulp** [comment]
Your plan sounds fine to me as-is.

If you will also create a basic Changelog in the format described by [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), I would appreciate it. Obviously for v0.1 there is not much to say, but it puts the infrastructure in place.

**Comment by kulp** [comment]
I do not think you can create tags yourself in this repository, although if you can, go ahead and create a `v0.1` tag when you think it is appropriate. Otherwise, let me know what Git revision you would like me to tag.

**Comment by madebr** [comment]
The first release has just been done!!

 :fireworks: :clap:
